@hostname = http://localhost:3001
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFycm1hbmk4OCIsImlkIjoxLCJpYXQiOjE2NTU0NzAyNjB9.jwbDc_qdpzlc14n7er7XU1VH8zuByKtBZ-nDNxWnCPo
### ------------------------------- REGISTER -------------------------------
POST {{hostname}}/register
Content-Type: application/json

{
    "firstName": "anas",
    "lastName": "el boudali",
    "username": "arrmani88",
    "email": "a@a.com",
    "password": "Q@qweqwe123"
}

# username: between 2 & 35 characters, and can be alphanumeric
# password: between 6 and 20 characters
# -------------------------------------------------------------------------
### -------------------------- confirm PROFILE ---------------------------
GET {{hostname}}/confirm_email/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFycm1hbmk4OCIsImlkIjoxLCJpYXQiOjE2Njg3ODAwMzZ9.D99HJt1jGdPhgWaYFlQDZrPMLFpZ8aJwZsrYMtl8YkE
# -------------------------------------------------------------------------
### -------------------------- COMPLETE PROFILE ---------------------------
POST {{hostname}}/complete_profile
Content-Type: application/json
Authorization: {{"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNoemFiYWtoIiwiaWQiOjEsImlhdCI6MTY3MjI3NDEwNX0.xgAuoTNs-Y6gGgOKOgcEXMiwtzduWr1FZ5h9Un59xvw"}}

{
    "birthday": "1994-12-24",
    "gender": "M",
    "sexualPreferences": "F",
    "biography": "some dwescription ....",
    "city": "Casablanca",
    "latitude": 15.8018625,
    "longitude": 16.4505496,
    "tags": ["aa", "bb", "cc", "dd", "ee"]
}

// RECENTLY ADDED: city, long/lati
# 'birthday': should be like YYYY-MM-DD
# 'gender': should be either 'M', 'F' or 'N' (if not specified)
# 'sexualPreferences': should be either 'M', 'F' or 'N' (if not specified)
# -------------------------------------------------------------------------
### ----------------------------- LOGIN -----------------------------------
POST {{hostname}}/login
Content-Type: application/json

{
    "login": "chzabakh",
    "password": "qwe123QWE@"
}

# -------------------------------------------------------------------------
### ----------------------- UPLOAD PROFILE IMAGE --------------------------
POST {{hostname}}/upload_profile_image
Authorization: {{token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image"; filename="anas.jpeg"

< /Users/anel-bou/http_files/anas.jpeg
--boundary--
# image should be either '.jpg', '.jpeg', or '.png', and less than 1024*1024 bytes (1MB)
# -------------------------------------------------------------------------
### --------------------- UPLOAD MULTIPLE FEED IMAGES ---------------------
POST {{hostname}}/upload_feed_images
Authorization: {{token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="images"; filename="fCL.jpeg"
Content-Type: image/jpeg

< /Users/anel-bou/http_files/fCL.jpeg
--boundary
Content-Disposition: form-data; name="images"; filename="mgn.jpeg"
Content-Type: image/jpeg

< /Users/anel-bou/http_files/mgn.jpeg
--boundary
Content-Disposition: form-data; name="images"; filename="ana-zwin.jpeg"
Content-Type: image/jpeg

< /Users/anel-bou/http_files/ana-zwin.jpeg
--boundary--
# key-> images
# value-> between 1 and 4 images
# each image should be either '.jpg', '.jpeg', or '.png', and less than (1024*1024) bytes (1MB)
# -------------------------------------------------------------------------
### ------------------------- UPLOAD 1 FEED IMAGE -------------------------
POST {{hostname}}/upload_feed_images
Authorization: {{token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="images"; filename="1.jpg"
Content-Type: image/jpeg

< ~/Desktop/1.jpg
--boundary--
# key-> images
# value-> between 1 and 4 images
# each image should be either '.jpg', '.jpeg', or '.png', and less than (1024*1024) bytes (1MB)
# -------------------------------------------------------------------------
### ----------------------- SEND RESET PASSWORD EMAIL ---------------------
POST {{hostname}}/reset_password
Content-Type: application/json

{
    "login": "arrmani88"
}

# send either username or email under the key "login"
# -------------------------------------------------------------------------
### ---------------------------- RESET PASSWORD ---------------------------
POST {{hostname}}/reset_password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6ImFycm1hbmk4OCIsImlhdCI6MTY2ODQwOTUxN30.QIIPd619N5Wu46fAj9Oiy7JimTe2BzR5rQXyfsU933Q
Content-Type: application/json

{
    "password": "123123qwe"
}

# --------------------------------------------------------------------------
### ------------------------ UPDATE PROFILE DATA ---------------------------
POST {{hostname}}/update_profile
Authorization: {{token}}
Content-Type: application/json

{
    "newfirstName": "bb",
    "username": "arrmani88",
    "password": "qweqwe123",
    "oldTags": ["ee", "bb", "cc", "dd", "aa"],
    "newTags": ["11", "22", "33", "44", "55"]
}

# -------------------------------------------------------------------------
### --------------------------  LIKE PROFILE  -----------------------------
POST {{hostname}}/like
Authorization: {{token}}
Content-Type: application/json

{
    "likedID": 2
}

# -------------------------------------------------------------------------
### -------------------------- UNLIKE PROFILE -----------------------------
POST {{hostname}}/unlike
Authorization: {{token}}
Content-Type: application/json

{
    "unlikedID": 2
}

# -------------------------------------------------------------------------
### --------------------------  DROP PROFILE  -----------------------------
POST {{hostname}}/drop
Authorization: {{token}}
Content-Type: application/json

{
    "dropedID": 2
}

# -------------------------------------------------------------------------

### --------------------------  BLOCK PROFILE -----------------------------
POST {{hostname}}/block
Authorization: {{token}}
Content-Type: application/json

{
    "blockedID": 2
}

# -------------------------------------------------------------------------
### -------------------------- UNBLOCK PROFILE ----------------------------
POST {{hostname}}/unblock
Authorization: {{token}}
Content-Type: application/json

{
    "unblockedID": 2
}

# -------------------------------------------------------------------------
### ------------------------- GET BLOCKED USERS ---------------------------
GET {{hostname}}/get_blocked_users
Authorization: {{token}}

# -------------------------------------------------------------------------
### ------------------------- DELETE FEED IMAGES --------------------------
POST {{hostname}}/delete_feed_images
Authorization: {{token}}
Content-Type: application/json

{
    "images": [
        "1657051058401_799bad5a3b514f096e69bbc4a7896cd9.jpg",
        "1657051058399_156005c5baf40ff51a327f1c34f2975b.jpg"
    ]
}

# -------------------------------------------------------------------------
### ------------------------------ GET USER -------------------------------
GET {{hostname}}/get_user
Authorization: {{token}}
Content-Type: application/json

{
    "id": 1
}

# -------------------------------------------------------------------------
### ------------------------------ GET LIKERS ------------------------------
GET {{hostname}}/get_likers
Authorization: {{token}}
# -------------------------------------------------------------------------
### ---------------------------- GET VISITORS -----------------------------
GET {{hostname}}/get_visitors
Authorization: {{token}}

# -------------------------------------------------------------------------
### --------------------------- GET FEDD USERS ----------------------------
GET {{hostname}}/get_feed_users
Authorization: {{token}}
Content-Type: application/json

{
    "ageMin": 1,
    "ageMax": 3001,
    "ratingMin": 0,
    "ratingMax": 100,
    "distance": 10000,
    "commonTagsIDs": [1, 2, 3, 4, 5],
    "pageNb": 1,
    "userPerPage": 100
}

# -------------------------------------------------------------------------
### ------------------------------- GET ME --------------------------------
GET {{hostname}}/get_me
Authorization: {{token}}

# -------------------------------------------------------------------------